database:
  host: localhost
  port: 4444
  user: choerrypagent
  password: 123456
  dbname: choerrypdb
  sslmode: disable
  schema: public

server:
  port: 1323
  allowOrigins:
    - "*"
  timeout: 30 # Seconds
  bodyLimit: "10M" # MiB
