database:
  host: localhost
  port: 5432
  user: myuser
  password: mypassword
  dbname: mydatabase
  sslmode: disable
  schema: public

server:
  port: 1323
  allowOrigins:
    - "*"
  timeout: 30
  bodyLimit: "1048576"
